# Generated by Django 3.1.2 on 2022-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
